spring:
  profiles:
    active: ${APP_ENV:development}
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:mem:mydb
    username: ejc
    password: password
    driverClassName: org.h2.Driver
    jpa:
      spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
      open-in-view: false
  mail:
    host: ${MAIL_HOST:localhost}
    port: ${MAIL_PORT:1025}
    username: ${MAIL_USERNAME:mailejc}
    password: ${MAIL_PASSWORD:null}
    from_address: ${MAIL_NOREPLY:no-reply@exchange_currency.co.mz}
    from_name: ${MAIL_FROMNAME:exchange_currency}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  flyway:
    clean-on-validation-error: true
    locations: classpath:/db/migration, classpath:/db/seeders
